name="GPGServices"
appName="GPGServices.service"

rmName="Uninstall.app"
imgBackground="Installer/background_dmg.png"
volumeLayout="Installer/DS_Store"


unset REVISION PRERELEASE
#REVISION=1
#PRERELEASE=b8





MAJOR=1
MINOR=8

source "$(dirname "${BASH_SOURCE[0]}")/Dependencies/GPGTools_Core/newBuildSystem/versioning.sh"
