name="GPGServices"
bundleName="$name.mpkg"
appName="$bundleName"
#todo: use CFBundleShortVersionString instead
version="1.7a4"
pkgProj="Installer/$name.pkgproj"
pkgReadme="Installer/INSTALLER.txt"
pkgInfo="Resources/Info.plist"
rmName="Uninstall.app"
rmPath="Installer/$rmName"
bundlePath="build/$appName"
imgBackground="./Installer/background_dmg.png";
dmgUrl="GPGTools/GPGServices"
