name="GPGServices"
version="1.4"
bundleName="$name.mpkg"
pkgProj="$name.pkgproj"
rmName="Uninstall.app"
rmPath="Installer/$rmName"
bundlePath="build/$appName"
imgBackground="./Installer/background_dmg.png";
